# Generated by Django 4.2.3 on 2023-08-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='to_currency',
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='accounts.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currency')),
            ],
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencypair'),
            preserve_default=False,
        ),
    ]
